Update views_api.py
As of 2023/06/26, the line "from werkzeug.util import safe_join" throws an error 

"from werkzeug.utils import safe_join
ImportError: cannot import name 'safe_join' from 'werkzeug.utils' (/usr/lib/python3/dist-packages/werkzeug/utils.py)
"
There is no safe_join in utils, but there is one in security. There does not appear to be any difference upon testing.